spring:
  profiles:
    active: local # 샘플 데이터 추가 시 테스트에 영향을 주지 않도록 프로파일 분리
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 매 실행마다 테이블 다시 생성
    properties:
      hibernate:
#        show_sql: true -> SQL를 System.out으로 출력
        format_sql: true # 출력을 이쁘게

logging:
  level:
    org.hibernate.SQL: debug # SQL를 로거를 통해 출력